// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnpiewcbrelucsixhsxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZucGlld2NicmVsdWNzaXhoc3h2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NDg3MTUsImV4cCI6MjA1NzUyNDcxNX0.9RbVZsf0eP0TAFvVfCmOK7AhAPOt9fYzcEJ6yjSuW94";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);